### ISSUE TITLE
OMG-

### ISSUE THREAD

**Issue by VillainsRule4000** [notzastix/betastar.js#2]
Can you make a way to get the user of the message (maybe in message.author idk)
Also a way to fetch the API, such as /api/user, or /api/user/elements?

Thanks, I'm already building TrollBot v1.0 :trollface:

**Comment by notzastix** [comment]
Yeah I will, thanks for the suggestion!

**Comment by notzastix** [comment]
Ive implemented .author and .content you can take a look at the message object at https://github.com/notzastix/betastar.js/blob/main/Documentation.md#attributes-1

**Comment by notzastix** [comment]
> Can you make a way to get the user of the message (maybe in message.author idk) Also a way to fetch the API, such as /api/user, or /api/user/elements?
> 
> Thanks, I'm already building TrollBot v1.0 :trollface:

Also their is no way to request the endpoints included in the lib but with `client.token` you can get the PHPSESSID which can be used in requests with axios
